name: Create binary files for every supported platform
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - ubuntu-20.04
          # - macos-latest,
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.21
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.15.0
          architecture: x64
          scope: super-protocol
      - name: Install make
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install make
      - name: Install dependencies
        run: npm ci
        shell: pwsh
      - name: Build binaries
        run: npm run prebuild
      - name: Build binaries for M1
        if: startsWith(matrix.os, 'macos')
        run: npm run prebuild -- -a arm64
      - name: "Save build results for release job"
        uses: actions/upload-artifact@v3
        with:
          name: prebuilt-binaries
          path: prebuilds/@super-protocol/*
          retention-days: 1
      - name: Upload binaries to GitHub Release
        run: npm run upload -- --upload-all ${{ github.token }}
